[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
wgpu = "26.0.1"
env_logger = "0.11.8"
pollster = "0.4.0"
log = "0.4"
image = "0.25.6"

tracing = "0.1"
tracing-subscriber = "0.3"
tracing-flame = "0.2"

rendering = { path = "../rendering" }